### ISSUE TITLE
Holidays seed

### ISSUE THREAD

**Issue by khalyomede** [LaravelDaily/Laravel-useful-seeds#2]
I learned about your package from this tweet: https://twitter.com/PovilasKorop/status/1452992673565093896, great initiative!

One idea came across my mind: for stats purposes at my job, we needed to know when the holidays events are occurring (to know how many of our customers are converted during these times for example).

I guess there is existing APIs that provide this data, but having the ability to filter on the query level is faster.

The downside for this idea are that:

- the data must be up to date (in case new holidays are added)
- this means seeded data might be obsolete (if a government decides to add an holiday in the middle of a year for example) - problematic for algorithm that relies on this data (meeting apps, etc...)
- can become big because we need to do one per country (is there cases when a lower granularity is needed, for example per region?)

I assume API providers encounter the same issues, so 🤷‍♂️

**Comment by PovilasKorop** [comment]
@khalyomede thanks for the suggestion. Do you have any list of data or API providers that we could use as a source of those holidays?

**Comment by khalyomede** [comment]
Of course, I know this one at least, and I will try to edit my answer with more to provide a variety of examples:

- https://github.com/public-apis/public-apis#calendar

**Comment by PovilasKorop** [comment]
@khalyomede checked those. Some of them are not free, and all of them are not easy to extract data from.

See this example, so I (or someone) would have to MANUALLY copy all the data line by line? https://github.com/nager/Nager.Date/tree/master/src/Nager.Date/PublicHolidays

I feel it's too big manual work you're asking for, sorry.

**Comment by khalyomede** [comment]
No problem, I got fooled by the fact they were listed in a list of public API.

I found some others, this time from official government APIs. I think I can contribute with a PR if needed:

- England (why is there a mention to "banks"?): https://www.api.gov.uk/gds/bank-holidays/
- France: https://www.data.gouv.fr/fr/datasets/jours-feries-en-france/

If other folks know officials government API listing holidays, we could aggregate more countries. What do you think?

**Comment by PovilasKorop** [comment]
@khalyomede not sure, not sure... Do you think it would be THAT useful, considering the amount of work required?

In my 20 years of web development, I've never had to use country holidays in any project.

**Comment by khalyomede** [comment]
I agree with you, fair enough! I propose to close this issue, and if folks really need this they will react to this thread.
